name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build
        env:
                  env:
          VITE_G1: ${{ secrets.VITE_G1 }}
          VITE_G2: ${{ secrets.VITE_G2 }}

          VITE_TTS1: ${{ secrets.VITE_TTS1 }}
          VITE_TTS2: ${{ secrets.VITE_TTS2 }}
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Vite builds into the 'dist' folder
          branch: gh-pages # This sends the "baked" code to your live site
